# Install script for directory: /media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/media/yunxiangyang/Train/omniGS/.deps/opencv-install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-readme.htm" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/icv/readme.htm")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-EULA.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/EULA.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-third-party-programs.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/third-party-programs.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-support.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/icv/../iw/../support.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-third-party-programs.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/icv/../iw/../third-party-programs.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-EULA.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippicv/ippicv_lnx/icv/../iw/../EULA.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "opencl-headers-LICENSE.txt" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/3rdparty/include/opencl/LICENSE.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ade-LICENSE" FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ade/ade-0.1.2a/LICENSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/cvconfig.h")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/opencv2/opencv_modules.hpp")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake"
         "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES
    "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/unix-install/OpenCVConfig-version.cmake"
    "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/unix-install/OpenCVConfig.cmake"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xscriptsx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/CMakeFiles/install/setup_vars_opencv4.sh")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/opencv4" TYPE FILE FILES
    "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/platforms/scripts/valgrind.supp"
    "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/platforms/scripts/valgrind_3rdparty.supp"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/libwebp/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/openjpeg/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ippiw/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/protobuf/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/quirc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/3rdparty/ittnotify/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/include/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/core/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/dnn/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/features2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/flann/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/gapi/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/highgui/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/java/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/js/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/ml/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/objc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/photo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/python/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/stitching/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/ts/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/video/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/videoio/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/world/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/alphamat/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/aruco/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/barcode/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/ccalib/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cudev/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/cvv/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/datasets/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/dpm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/face/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/freetype/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/hdf/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/hfs/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/img_hash/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/intensity_transform/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/julia/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/matlab/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/mcc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/optflow/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/ovis/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/plot/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/quality/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/rapid/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/reg/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/rgbd/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/saliency/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/sfm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/shape/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/stereo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/structured_light/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/superres/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/text/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/tracking/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/videostab/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/viz/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/wechat_qrcode/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/.firstpass/xphoto/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudev/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/python_tests/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/core/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudaarithm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/flann/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/imgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/intensity_transform/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/ml/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/phase_unwrapping/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/plot/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/quality/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/reg/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/surface_matching/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/alphamat/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudafilters/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudaimgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudawarping/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/dnn/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/dnn_superres/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/features2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/freetype/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/fuzzy/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/hfs/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/img_hash/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/imgcodecs/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/line_descriptor/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/photo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/saliency/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/text/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/videoio/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/xphoto/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/barcode/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/calib3d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudacodec/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudafeatures2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudastereo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/datasets/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/highgui/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/mcc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/objdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/rapid/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/rgbd/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/shape/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/structured_light/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/video/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/wechat_qrcode/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/xfeatures2d/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/ximgproc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/xobjdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/aruco/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/bgsegm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/bioinspired/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/ccalib/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudabgsegm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudalegacy/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudaobjdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/dnn_objdetect/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/dpm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/face/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/gapi/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/js_bindings_generator/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/optflow/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/sfm/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/stitching/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/tracking/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/cudaoptflow/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/java_bindings_generator/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/objc_bindings_generator/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/stereo/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/superres/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/videostab/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/modules/python_bindings_generator/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/doc/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/data/cmake_install.cmake")
  include("/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/apps/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/media/yunxiangyang/Train/omniGS/.deps/opencv-4.7.0/build_cuda/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
